### Global Options ###
directory: /opt/library
library: /opt/.beets/MusicLibrary.db

paths:
    default: %the{$albumartist}/($year) $album/$disc-$track $title

original_date: yes
per_disc_numbering: yes
max_filename_length: 64


### UI Options ###
ui:
    color: yes


### Importer Options ###
import:
    log: /opt/.beets/ImportLog.txt
    timid: yes

### Plugin Options ###
plugins: badfiles edit lastgenre scrub the

# Bad Files Plugin
badfiles:
    commands:
        flac: flac --test --warnings-as-errors --silent

# Import genres from Last.fm (MusicBrainz does not track genre info)
lastgenre:
    auto: yes
    count: 1
    force: yes
    whitelist: yes

# Scrub all tags not tracked by Beets
scrub:
    auto: yes

# Handle stripping and appending articles from filenames (see use of "%the" in "paths:" above)
the:
    a: yes
    the: yes
