FROM arm32v6/alpine:3.8
LABEL maintainer "Alex Haydock <alex@alexhaydock.co.uk>"

ADD docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
ADD torrc /etc/tor/torrc

RUN set -xe \
    \
# Install Tor
    && apk --no-cache add tor \
    \
# Set permissions on script
    && chmod +x /usr/bin/docker-entrypoint.sh

# Run
ENV HOME "/var/lib/tor"
WORKDIR ["/var/lib/tor"]
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
