#!/bin/sh

# default value for annotation timeout in seconds.
MAX_WAIT=${MAX_WAIT:-1800}

cd "${LIBRE_HOME}" || exit

exec \
	java -Dorg.eclipse.jetty.annotations.maxWait="${MAX_WAIT}" \
	-Dlibresonic.home="${LIBRE_SETTINGS}" \
	-Dlibresonic.defaultMusicFolder=/music \
	-Dlibresonic.defaultPodcastFolder=/podcasts \
	-Dlibresonic.defaultPlaylistFolder=/playlists \
	-jar /usr/share/java/jetty-runner.jar \
	--host 0.0.0.0 --port 4040 --path "/" \
	libresonic.war